## Numpy Practice

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [3]:
# Create a 1-dimensional NumPy array
array1=np.array([5,1,7])
array1

array([5, 1, 7])

In [5]:
# Create a 2-dimensional NumPy array
array2=np.array([[2,3,4],
                [9,1,6]])
array2

array([[2, 3, 4],
       [9, 1, 6]])

In [6]:
# Create a 3-dimensional Numpy array
array3=np.array([[[0,2,5],
                 [1,4,7],
                 [3,6,9]],
                [[3,5,0],
                [7,6,2],
                [9,1,0]]])
array3

array([[[0, 2, 5],
        [1, 4, 7],
        [3, 6, 9]],

       [[3, 5, 0],
        [7, 6, 2],
        [9, 1, 0]]])

In [8]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
array1.shape, array1.ndim, array1.dtype, array1.size, type(array1)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [9]:
# Attributes of 2-dimensional array
array2.shape, array2.ndim, array2.dtype, array2.size, type(array2)

((2, 3), 2, dtype('int32'), 6, numpy.ndarray)

In [10]:
# Attributes of 3-dimensional array
array3.shape, array3.ndim, array3.dtype, array3.size, type(array3)

((2, 3, 3), 3, dtype('int32'), 18, numpy.ndarray)

In [11]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
data=pd.DataFrame(array2)
data

0  1  2
0  2  3  4
1  9  1  6

In [12]:
# Create an array of shape (10, 2) with only ones
ones=np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
# Create an array of shape (7, 2, 3) of only zeros
zeros=np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [16]:
# Create an array within a range of 0 and 100 with step 3
array4=np.arange(0,100,3)
array4

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [17]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
array5=np.random.randint(0,10,size=(7,2))
array5

array([[8, 4],
       [6, 4],
       [0, 5],
       [5, 3],
       [0, 2],
       [1, 9],
       [6, 8]])

In [18]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
array6=np.random.random((3,5))
array6

array([[0.70384647, 0.06751912, 0.32836484, 0.35776665, 0.31899221],
       [0.2550308 , 0.13797099, 0.94467545, 0.45989946, 0.980795  ],
       [0.61105986, 0.34371154, 0.39223031, 0.93897192, 0.65958704]])

In [19]:
# Set the random seed to 42
# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.seed(42)
array7=np.random.randint(0,10,size=(4,6))
array7

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [20]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
# Find the unique numbers in the array you just created
array8=np.random.randint(1,10,size=(3,7))
array8

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2],
       [4, 9, 2, 9, 5, 2, 4]])

In [21]:
np.unique(array8)

array([1, 2, 3, 4, 5, 7, 9])

In [22]:
# Find the 0'th index of the latest array you created
array8[0]

array([9, 1, 3, 7, 4, 9, 3])

In [23]:
# Get the first 2 rows of latest array you created
array8[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [24]:
# Get the first 2 values of the first 2 rows of the latest array
array8[:2,:2]

array([[9, 1],
       [5, 3]])

In [30]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
array9=np.random.randint(0,10,size=(3,5))
array10=np.ones((3,5))
array9

array([[9, 6, 9, 8, 6],
       [8, 7, 1, 0, 6],
       [6, 7, 4, 2, 7]])

In [31]:
# Add the two arrays together
np.add(array9,array10)

array([[10.,  7., 10.,  9.,  7.],
       [ 9.,  8.,  2.,  1.,  7.],
       [ 7.,  8.,  5.,  3.,  8.]])

In [33]:
# Create another array of ones of shape (3, 5)
ones1=np.ones((3,5))

In [34]:
# Subtract the new array of ones from the other most recent array
array9-ones1

array([[ 8.,  5.,  8.,  7.,  5.],
       [ 7.,  6.,  0., -1.,  5.],
       [ 5.,  6.,  3.,  1.,  6.]])

In [35]:
# Multiply the ones array with the latest array
array9*ones1

array([[9., 6., 9., 8., 6.],
       [8., 7., 1., 0., 6.],
       [6., 7., 4., 2., 7.]])

In [36]:
# Take the latest array to the power of 2
array9**ones1

array([[9., 6., 9., 8., 6.],
       [8., 7., 1., 0., 6.],
       [6., 7., 4., 2., 7.]])

In [37]:
# Do the same thing with np.square()
np.square(array9)

array([[81, 36, 81, 64, 36],
       [64, 49,  1,  0, 36],
       [36, 49, 16,  4, 49]], dtype=int32)

In [38]:
# Find the mean of the latest array
np.mean(array9)

5.733333333333333

In [39]:
# Find the maximum of the latest array
np.max(array9)

9

In [40]:
# Find the minimum of the latest array
np.min(array9)

0

In [41]:
# Find the standard deviation of the latest array
np.std(array9)

2.6948510575210314

In [42]:
# Find the variance of the latest array
np.var(array9)

7.2622222222222215

In [43]:
# Reshape the latest array to (3, 5, 1)
array9.reshape(3,5,1)

array([[[9],
        [6],
        [9],
        [8],
        [6]],

       [[8],
        [7],
        [1],
        [0],
        [6]],

       [[6],
        [7],
        [4],
        [2],
        [7]]])

In [44]:
# Transpose the latest array
array9.T

array([[9, 8, 6],
       [6, 7, 7],
       [9, 1, 4],
       [8, 0, 2],
       [6, 6, 7]])

In [45]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
a1=np.random.randint(0,10,size=(3,3))
a2=np.random.randint(0,10,size=(3,2))

In [46]:
# Perform a dot product on the two newest arrays you created
np.dot(a1,a2)

array([[ 46,  48],
       [ 62,  52],
       [113,  54]])

In [48]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
a3=np.random.randint(0,10,size=(4,3))
a4=np.random.randint(0,10,size=(4,3))

In [50]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(a3.T,a4)

array([[105, 105, 103],
       [ 38,  36,  94],
       [ 93,  90, 110]])

In [51]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
random1=np.random.randint(0,10,size=(4,4))
random2=np.random.randint(0,10,size=(4,4))

In [52]:
random1

array([[8, 3, 8, 2],
       [6, 5, 7, 8],
       [4, 0, 2, 9],
       [7, 5, 7, 8]])

In [53]:
random2

array([[3, 0, 0, 9],
       [3, 6, 1, 2],
       [0, 4, 0, 7],
       [0, 0, 1, 1]])

In [54]:
# Compare the two arrays with '>'
random1 > random2

array([[ True,  True,  True, False],
       [ True, False,  True,  True],
       [ True, False,  True,  True],
       [ True,  True,  True,  True]])

In [55]:
# Compare the two arrays with '>='
random1 >= random2

array([[ True,  True,  True, False],
       [ True, False,  True,  True],
       [ True, False,  True,  True],
       [ True,  True,  True,  True]])

In [57]:
# Find which elements of the first array are greater than 7
random1 > 7

array([[ True, False,  True, False],
       [False, False, False,  True],
       [False, False, False,  True],
       [False, False, False,  True]])

In [58]:
# Which parts of each array are equal?
random1 == random2

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [59]:
# Sort one of the arrays you just created in ascending order
np.sort(random1)

array([[2, 3, 8, 8],
       [5, 6, 7, 8],
       [0, 2, 4, 9],
       [5, 7, 7, 8]])

In [60]:
# Sort the indexes of one of the arrays you just created
np.argsort(random1)

array([[3, 1, 0, 2],
       [1, 0, 2, 3],
       [1, 2, 0, 3],
       [1, 0, 2, 3]], dtype=int64)

In [61]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(random1)

11

In [62]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(random1)

9

In [64]:
# Find the indexes with the maximum values down the 1st axis
# of one of the arrays you created
np.argmax(random1,axis=1)

array([0, 3, 3, 3], dtype=int64)

In [65]:
# Find the indexes with the minimum values across the 0th axis
# of one of the arrays you created
np.argmin(random1,axis=0)

array([2, 2, 2, 0], dtype=int64)

In [66]:
# Create an array of normally distributed random numbers
np.random.randn(3,2)

array([[-0.44176602, -0.08416509],
       [ 1.23701607, -1.42647888],
       [ 0.33802266,  1.9745712 ]])

In [68]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])